#![no_std]
#![no_main]
#![feature(type_alias_impl_trait)]

use core::str::FromStr;

use esp_backtrace as _;
use esp_hal::{
    system::SystemControl,
    clock::{ClockControl, CpuClock},
    peripherals::Peripherals,
    gpio::Io,
    rmt::Rmt,
    timer::{ErasedTimer, OneShotTimer},
    prelude::*,
};

use embassy_executor::Spawner;
use embassy_time::{Duration, Timer, Ticker};

use static_cell::make_static;
use esp_wifi::wifi::{
    AuthMethod, WifiController, WifiDevice, WifiEvent, WifiStaDevice, WifiState
};
use embassy_net::{tcp::TcpSocket, Config, Ipv4Address, Stack, StackResources};
use rust_mqtt::{
    client::{client::MqttClient, client_config::ClientConfig},
    packet::v5::{
        reason_codes::ReasonCode,
        publish_packet::QualityOfService,
    },
    utils::rng_generator::CountingRng,
};

// The constant `CONFIG` is auto-generated by `toml_config`.
#[toml_cfg::toml_config]
pub struct FirmwareConfig {
    #[default("")]
    wifi_ssid: &'static str,
    #[default("")]
    wifi_psk: &'static str,
    #[default("")]
    mqtt_host: &'static str,
    #[default("")]
    mqtt_port: &'static str,
    #[default("")]
    mqtt_user: &'static str,
    #[default("")]
    mqtt_pass: &'static str,
    #[default("")]
    mqtt_id: &'static str,
}

#[main]
async fn main(spawner: Spawner) -> ! {
    esp_println::logger::init_logger_from_env();

    let peripherals = Peripherals::take();
    let system = SystemControl::new(peripherals.SYSTEM);
    let clocks = ClockControl::configure(system.clock_control, CpuClock::Clock160MHz).freeze();


    // Network setup start
    let timer = esp_hal::timer::PeriodicTimer::new(
        esp_hal::timer::timg::TimerGroup::new(peripherals.TIMG1, &clocks, None)
            .timer0
            .into(),
    );
    let init = esp_wifi::initialize(
        esp_wifi::EspWifiInitFor::Wifi,
        timer,
        esp_hal::rng::Rng::new(peripherals.RNG),
        peripherals.RADIO_CLK,
        &clocks,
    )
    .unwrap();
    let (wifi_interface, controller) =
        esp_wifi::wifi::new_with_mode(&init, peripherals.WIFI, WifiStaDevice).unwrap();

    let systimer = esp_hal::timer::systimer::SystemTimer::new(peripherals.SYSTIMER);
    esp_hal_embassy::init(
        &clocks,
        make_static!(
            [OneShotTimer::new(systimer.alarm0.into())]
        ),
    );

    // Init network stack
    let seed = 1234; // very random, very secure seed
    let stack = &*make_static!(Stack::new(
        wifi_interface,
        Config::dhcpv4(Default::default()),
        make_static!(StackResources::<3>::new()),
        seed
    ));

    spawner.spawn(connection(controller)).ok();
    spawner.spawn(net_task(stack)).ok();

    let mut rx_buffer = [0; 4096];
    let mut tx_buffer = [0; 4096];

    // Outer loop that maintains WiFi connectivity
    loop {
        if stack.is_link_up() {
            break;
        }
        Timer::after(Duration::from_millis(500)).await;
    }

    log::info!("Waiting to get IP address...");
    loop {
        if let Some(config) = stack.config_v4() {
            log::info!("Got IP: {}", config.address);
            break;
        }
        Timer::after(Duration::from_millis(500)).await;
    }

    // Inner loop that maintains connectivity to the MQTT broker
    loop {
        let mut socket = TcpSocket::new(stack, &mut rx_buffer, &mut tx_buffer);
        socket.set_timeout(Some(embassy_time::Duration::from_secs(10)));
        let remote_endpoint = (Ipv4Address::from_str(FIRMWARE_CONFIG.mqtt_host).unwrap(), FIRMWARE_CONFIG.mqtt_port.parse::<u16>().unwrap());

        log::info!("connecting...");
        Timer::after(Duration::from_millis(500)).await;
        let r = socket.connect(remote_endpoint).await;
        if let Err(e) = r {
            log::info!("connect error: {:?}", e);
            continue;
        }
        log::info!("connected!");

        let mut config = ClientConfig::new(
            rust_mqtt::client::client_config::MqttVersion::MQTTv5,
            CountingRng(20000),
        );
        config.add_max_subscribe_qos(rust_mqtt::packet::v5::publish_packet::QualityOfService::QoS1);
        config.add_client_id(FIRMWARE_CONFIG.mqtt_id);
        config.add_username(FIRMWARE_CONFIG.mqtt_user);
        config.add_password(FIRMWARE_CONFIG.mqtt_pass);
        config.max_packet_size = 100;
        let mut recv_buffer = [0; 80];
        let mut write_buffer = [0; 80];
        let mut client = MqttClient::<_, 5, _>::new(
            socket,
            &mut write_buffer,
            80,
            &mut recv_buffer,
            80,
            config,
        );
        while let Err(result) = client.connect_to_broker().await {
            if result == ReasonCode::Success {
                log::info!("connected!");
                break;
            }
            else {
                log::error!("Could not contact broker because {result}")
            }
            Timer::after(Duration::from_millis(500)).await;
            log::info!("Attempting again...");
        }

        // Main loop that sends data to the broker
        let mut ticker = Ticker::every(Duration::from_secs(1));
        let mut i: i32 = 0;
        loop {
            i += 1;
            if let Err(result) = client
                .send_message(
                    "imu0/event",
                    &i.to_be_bytes(),
                    QualityOfService::QoS0,
                    true,
                )
                .await {
                if result != ReasonCode::Success {
                    log::error!("Could not publish because {result}; Restarting connection!");
                    break;
                }
            }
            ticker.next().await;
        }
    }

}

#[embassy_executor::task]
async fn connection(mut controller: WifiController<'static>) {
    log::info!("start connection task");
    log::info!("Device capabilities: {:?}", controller.get_capabilities());
    loop {
        if esp_wifi::wifi::get_wifi_state() == WifiState::StaConnected {
            // wait until we're no longer connected
            controller.wait_for_event(WifiEvent::StaDisconnected).await;
            Timer::after(Duration::from_millis(5000)).await
        }
        if !matches!(controller.is_started(), Ok(true)) {
            let client_config = esp_wifi::wifi::Configuration::Client(esp_wifi::wifi::ClientConfiguration {
                ssid: FIRMWARE_CONFIG.wifi_ssid.parse().unwrap(),
                password: FIRMWARE_CONFIG.wifi_psk.parse().unwrap(),
                auth_method: AuthMethod::WPA2Personal,
                ..Default::default()
            });
            controller.set_configuration(&client_config).unwrap();
            log::info!("Starting wifi");
            controller.start().await.unwrap();
            log::info!("Wifi started!");
        }
        log::info!("About to connect...");

        match controller.connect().await {
            Ok(_) => log::info!("Wifi connected!"),
            Err(e) => {
                log::error!("Failed to connect to wifi: {e:?}");
                Timer::after(Duration::from_millis(5000)).await
            }
        }
    }
}

#[embassy_executor::task]
async fn net_task(stack: &'static Stack<WifiDevice<'static, WifiStaDevice>>) {
    stack.run().await
}